-- Create bank_accounts table if it doesn't exist
CREATE TABLE IF NOT EXISTS bank_accounts (
  id INT PRIMARY KEY AUTO_INCREMENT,
  company_id INT NOT NULL DEFAULT 1,
  account_name VARCHAR(255) NULL,
  account_number VARCHAR(100) NULL,
  bank_name VARCHAR(255) NULL,
  bank_code VARCHAR(50) NULL,
  branch_name VARCHAR(255) NULL,
  branch_code VARCHAR(50) NULL,
  swift_code VARCHAR(50) NULL,
  iban VARCHAR(100) NULL,
  account_type VARCHAR(50) NULL,
  routing_number VARCHAR(50) NULL,
  currency VARCHAR(10) DEFAULT 'USD',
  opening_balance DECIMAL(15,2) DEFAULT 0,
  current_balance DECIMAL(15,2) DEFAULT 0,
  address TEXT NULL,
  city VARCHAR(100) NULL,
  state VARCHAR(100) NULL,
  zip VARCHAR(20) NULL,
  country VARCHAR(100) NULL,
  contact_person VARCHAR(255) NULL,
  phone VARCHAR(50) NULL,
  email VARCHAR(255) NULL,
  notes TEXT NULL,
  status VARCHAR(50) DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted TINYINT(1) DEFAULT 0,
  INDEX idx_company_id (company_id),
  INDEX idx_is_deleted (is_deleted)
);

