CREATE TABLE IF NOT EXISTS `offers` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT UNSIGNED NOT NULL,
  `offer_number` VARCHAR(50) NOT NULL UNIQUE,
  `valid_till` DATE NOT NULL,
  `offer_date` DATE NULL,
  `currency` VARCHAR(10) DEFAULT 'USD',
  `client_id` INT UNSIGNED NULL,
  `lead_id` INT UNSIGNED NULL,
  `project_id` INT UNSIGNED NULL,
  `calculate_tax` ENUM('After Discount', 'Before Discount') DEFAULT 'After Discount',
  `description` TEXT NULL,
  `note` TEXT NULL,
  `terms` TEXT DEFAULT 'Thank you for your business.',
  `discount` DECIMAL(15, 2) DEFAULT 0.00,
  `discount_type` ENUM('%', 'fixed') DEFAULT '%',
  `sub_total` DECIMAL(15, 2) DEFAULT 0.00,
  `discount_amount` DECIMAL(15, 2) DEFAULT 0.00,
  `tax_amount` DECIMAL(15, 2) DEFAULT 0.00,
  `tax` VARCHAR(50) NULL,
  `second_tax` VARCHAR(50) NULL,
  `total` DECIMAL(15, 2) DEFAULT 0.00,
  `status` ENUM('Draft', 'Sent', 'Accepted', 'Declined', 'Expired', 'Waiting') DEFAULT 'Draft',
  `created_by` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `offer_items` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `offer_id` INT UNSIGNED NOT NULL,
  `item_name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `quantity` DECIMAL(10, 2) DEFAULT 1.00,
  `unit` ENUM('Pcs', 'Kg', 'Hours', 'Days') DEFAULT 'Pcs',
  `unit_price` DECIMAL(15, 2) NOT NULL,
  `tax` VARCHAR(50) NULL,
  `tax_rate` DECIMAL(5, 2) DEFAULT 0.00,
  `file_path` VARCHAR(500) NULL,
  `amount` DECIMAL(15, 2) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`offer_id`) REFERENCES `offers`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `deals` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT UNSIGNED NOT NULL,
  `deal_number` VARCHAR(50) NOT NULL UNIQUE,
  `valid_till` DATE NOT NULL,
  `deal_date` DATE NULL,
  `currency` VARCHAR(10) DEFAULT 'USD',
  `client_id` INT UNSIGNED NULL,
  `lead_id` INT UNSIGNED NULL,
  `project_id` INT UNSIGNED NULL,
  `title` VARCHAR(255) NULL,
  `calculate_tax` ENUM('After Discount', 'Before Discount') DEFAULT 'After Discount',
  `description` TEXT NULL,
  `note` TEXT NULL,
  `terms` TEXT DEFAULT 'Thank you for your business.',
  `discount` DECIMAL(15, 2) DEFAULT 0.00,
  `discount_type` ENUM('%', 'fixed') DEFAULT '%',
  `sub_total` DECIMAL(15, 2) DEFAULT 0.00,
  `discount_amount` DECIMAL(15, 2) DEFAULT 0.00,
  `tax_amount` DECIMAL(15, 2) DEFAULT 0.00,
  `tax` VARCHAR(50) NULL,
  `second_tax` VARCHAR(50) NULL,
  `total` DECIMAL(15, 2) DEFAULT 0.00,
  `status` ENUM('Draft', 'Sent', 'Accepted', 'Declined', 'Expired') DEFAULT 'Draft',
  `created_by` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `deal_items` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `deal_id` INT UNSIGNED NOT NULL,
  `item_name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `quantity` DECIMAL(10, 2) DEFAULT 1.00,
  `unit` ENUM('Pcs', 'Kg', 'Hours', 'Days') DEFAULT 'Pcs',
  `unit_price` DECIMAL(15, 2) NOT NULL,
  `tax` VARCHAR(50) NULL,
  `tax_rate` DECIMAL(5, 2) DEFAULT 0.00,
  `file_path` VARCHAR(500) NULL,
  `amount` DECIMAL(15, 2) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`deal_id`) REFERENCES `deals`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
